### PR TITLE
Fa5 compatibility

### PR DESCRIPTION
**Pull request by lavolp3**
Arrows symbol did not work anymore in new MM version.
Changing class prefix to "fas" ("fa" is deprecated in FA5) and name to arrows-alt-h (free for non-pro FA5 users) got them back again.
Can not yet see any other symbol disappearing from this action

### CODE REVIEW

**Comment by ianperrin** [comment]
Hi @lavolp3 

Thanks for the contribution. Much appreciated.

It looks like v2.6.0 has introduced a bug with introducing support of FA5. 

If you remove any module which references FA5 (e.g. the calendar module), then the arrows symbol appears. Including these updated modules causes the arrow symbol doesn't appear.

Your pull request goes someway to fixing the issue, providing that
1. MagicMirror v2.6.0 is installed
1. Another module which references FA5 is included in `config.js` 

You can replicate this by applying the changes to the module installed in an older version of MagicMirror or modifying the `config.js` file so that it only includes MMM-Strava. In both these cases, all icons do not appear.

To fix this, 
1. The [minimum version](https://github.com/MichMich/MagicMirror/blob/master/modules/README.md#requiresversion) of MagicMirror required by the module must be specified. e.g. by adding the following above [L13 in MMM-Strava](https://github.com/ianperrin/MMM-Strava/blob/2f4b45607d3f36345ab443ffe7cb73dbe329b66a/MMM-Strava.js#L13): `requiresVersion: "2.6.0",`
1. FontAwesome5 must be referenced in MMM-Strava's `getStyles` function. It looks like the [MagicMirror documentation](
https://github.com/MichMich/MagicMirror/blob/master/modules/README.md#getstyles) for using FA5 has not been updated since v2.6.0 was released last week. However, based on the [changes made to the default calendar module](https://github.com/MichMich/MagicMirror/blob/fc89feec4ebf07a8688c4c0511bb22422b1f5165/modules/default/calendar/calendar.js#L54) when FA5 was added,  [line 44 of MMM-Strava.js](https://github.com/ianperrin/MMM-Strava/blob/2f4b45607d3f36345ab443ffe7cb73dbe329b66a/MMM-Strava.js#L44) should be amended to read `return ['font-awesome5.css', 'MMM-Strava.css'];` Note: I don't believe `'font-awesome5.v4shims.css',` is required as you have change the class from `fa` to `fas` - this eliminating the need for FA4 compatibility within this module, but this needs testing.

If you can make and test these changes, I can merge the pull. In the meantime, I'll raise a bug to see if it can be fixed

Thanks again

**Comment by lavolp3** [comment]
Understood. So it's a bit more complicated. Do I understand right, that some module or process determines that MM uses FA5 and not FA4?
Then when you only use MMM-Strava, FA4 is used and my amendment does not work. 
Interesting.
I'll work on it.
I heard that MM was going to use FA5 but was of the impression that it was backwards compatible.

**Comment by lavolp3** [comment]
can't we just include "font-awesome5.v4shims.css" into the getStyles part as well?

**Comment by ianperrin** [comment]
@lavolp3 - I've submitted a pull request to the core MM code which should fix the issue with multiple versions of FA requested by modules.

Once this is released (in version 2.7 hopefully ), the distance icon will reappear and this pull request will not be required

Thanks

**Comment by ianperrin** [comment]
I'm closing this pull request now that version 2.7 has been released which contains the fix for the font awesome issue (see MichMich/MagicMirror#1525)

**Pull request closed without merging**
