### PR TITLE
Pacemaker

### PR DESCRIPTION
**Pull request by lavolp3**
> Please send your pull requests the `develop` branch.
> Don't forget to update the README.md.

* Does the pull request solve a **related** issue?

No

* If so, can you reference the issue?

* What does the pull request accomplish? Use a list if needed.

Includes "pace" as choice to the table view.
Pace will be shown according to config.units:

for running: in min/km or min/mi
for cycling: in km/h or mi/h
for swimming: in min/100m or min/100ys

* If it includes major visual changes please add screenshots.

NO major visual change

### CODE REVIEW

**Comment by ianperrin** [comment]
Hi @lavolp3 - interesting.

If the spirit of consistency, could you move the code which calculates the _pace_ from [node_helper.js](https://github.com/ianperrin/MMM-Strava/pull/29/files#diff-f7c0e2621975f4cab14c8d9cbe636dd4) to a nunjucks filter in [MMM-Strava.js](https://github.com/ianperrin/MMM-Strava/blob/3b0f883ceaa0d38398715742fab36108d22342f5/MMM-Strava.js#L204)?

It looks like you've already started this with the `getPace` function but not completed it.

Thanks

**Comment by lavolp3** [comment]
You're right I completely forgot the getPace function which is currently useless.
I had preferred to add the pace to the array of data to use it later in the template like the other properties.

I'll try to include it in the main js.

**Comment by lavolp3** [comment]
I've thought about your inquiry some time now and tried some things, but in my view it is incredibly more difficult to calculate the pace using the main .js and the template.
By generating it in the node_helper you already have it in the data array after every call for every activity and period.
Later on you need to extract distance and time from every activity and every period, calculate the pace and show it.
If I understand nunjucks correctly it works with filters using ONE variable and doing something with it. Here I need several so I need to calculate the pace somewhere in the main .js. However, at that point I need to know which activity and period is asked for.

I need your help or I need to give up. This has become much too complex for me.

**Comment by lavolp3** [comment]
my original PR has been messed up by an internal merge. Have to say I'm new to this :-)

**Pull request closed without merging**
